<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <Configurations>MassEffect - Debug;MassEffect - Release;SWBF2 - Debug;SWBF2 - Release;GW2 - Debug;GW2 - Release;GW1 - Debug;GW1 - Release</Configurations>
    <Platforms>x64</Platforms>
    <TargetFrameworks>net48</TargetFrameworks>
    <AssemblyTitle>LevelEditorPlugin</AssemblyTitle>
    <Product>LevelEditorPlugin</Product>
    <Copyright>Copyright ©  2020</Copyright>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <UseWPF>true</UseWPF>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='MassEffect - Debug|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Developer\Debug\</OutputPath>
    <DefineConstants>TRACE;DEBUG;MASS_EFFECT</DefineConstants>
  </PropertyGroup>
  
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release - Alpha|x64' ">
    <OutputPath>bin\Release\Alpha\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Beta|x64'">
    <OutputPath>bin\Release\Beta\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='MassEffect - Release|x64'">
    <OutputPath>bin\Release\Final\</OutputPath>
    <DefineConstants>TRACE;MASS_EFFECT</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='SWBF2 - Release|x64'">
    <OutputPath>bin\Release\Final\</OutputPath>
    <DefineConstants>TRACE;SWBF2</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>
  
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'GW2 - Debug|x64' ">
    <DefineConstants>TRACE;DEBUG;GW2</DefineConstants>
  </PropertyGroup>
  
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'GW2 - Release|x64' ">
    <DefineConstants>TRACE;GW2</DefineConstants>
  </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'GW1 - Debug|x64' ">
        <DefineConstants>TRACE;DEBUG;GW1</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'GW1 - Release|x64' ">
        <DefineConstants>TRACE;GW1</DefineConstants>
    </PropertyGroup>
  
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'SWBF2 - Debug|x64' ">
    <DefineConstants>TRACE;DEBUG;SWBF2</DefineConstants>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MassEffect - Debug|net48|x64'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MassEffect - Release|net48|x64'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='SWBF2 - Release|net48|x64'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='SWBF2 - Debug|net48|x64'">
    <OutputPath>bin\Developer\Debug\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>TRACE;SWBF2</DefineConstants>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release - Final|net48|x64'">
    <DefineConstants>TRACE;MASS_EFFECT</DefineConstants>
    <OutputPath>bin\Release\Final\</OutputPath>
  </PropertyGroup>
   
  <ItemGroup>
    <None Remove="Images\BeamBlueprintFileType.png" />
    <None Remove="Images\Bottom.png" />
    <None Remove="Images\BottomLeft.png" />
    <None Remove="Images\BottomRight.png" />
    <None Remove="Images\CaptureThumbnail.png" />
    <None Remove="Images\ClearLayout.png" />
    <None Remove="Images\Components.png" />
    <None Remove="Images\ConnectorOrder.png" />
    <None Remove="Images\CurvedWire.png" />
    <None Remove="Images\Delay.png" />
    <None Remove="Images\Float.png" />
    <None Remove="Images\GameObjectBlueprintFileType.png" />
    <None Remove="Images\GameView.png" />
    <None Remove="Images\HoleMask.png" />
    <None Remove="Images\Input.png" />
    <None Remove="Images\Instances.png" />
    <None Remove="Images\Interface.png" />
    <None Remove="Images\Layers.png" />
    <None Remove="Images\LevelDataIcon.png" />
    <None Remove="Images\ObjectBlueprintFileType.png" />
    <None Remove="Images\PowerBlueprintFileType.png" />
    <None Remove="Images\ProjectileBlueprintFileType.png" />
    <None Remove="Images\Properties.png" />
    <None Remove="Images\Schematics.png" />
    <None Remove="Images\SoldierBlueprintFileType.png" />
    <None Remove="Images\Terrain.png" />
    <None Remove="Images\ThumbnailSafezone.png" />
    <None Remove="Images\Timeline.png" />
    <None Remove="Images\Toolbox.png" />
    <None Remove="Images\TopLeft.png" />
    <None Remove="Images\TopRight.png" />
    <None Remove="Images\Tracks\AntTrack.png" />
    <None Remove="Images\Tracks\BoolTrack.png" />
    <None Remove="Images\Tracks\CameraTrack.png" />
    <None Remove="Images\Tracks\ColorTrack.png" />
    <None Remove="Images\Tracks\ConversationTrack.png" />
    <None Remove="Images\Tracks\DirectorTrack.png" />
    <None Remove="Images\Tracks\DofTrack.png" />
    <None Remove="Images\Tracks\EntityTrack.png" />
    <None Remove="Images\Tracks\EventTrack.png" />
    <None Remove="Images\Tracks\FaceEmotionTrack.png" />
    <None Remove="Images\Tracks\FadeTrack.png" />
    <None Remove="Images\Tracks\FloatTrack.png" />
    <None Remove="Images\Tracks\LayerTrack.png" />
    <None Remove="Images\Tracks\LookAtTrack.png" />
    <None Remove="Images\Tracks\PathTrack.png" />
    <None Remove="Images\Tracks\TransformTrack.png" />
    <None Remove="Images\Tracks\Vec2Track.png" />
    <None Remove="Images\Tracks\Vec3Track.png" />
    <None Remove="Images\Tracks\Vec4Track.png" />
    <None Remove="Images\Types\DetachedSubWorldFileType.png" />
    <None Remove="Images\Types\EffectBlueprintFileType.png" />
    <None Remove="Images\Types\LayerDataFileType.png" />
    <None Remove="Images\Types\LensFlareBlueprintFileType.png" />
    <None Remove="Images\Types\LevelDataFileType.png" />
    <None Remove="Images\Types\SubWorldFileType.png" />
    <None Remove="Images\Types\VehicleBlueprintFileType.png" />
    <None Remove="Images\Types\VisualEnvironmentFileType.png" />
    <None Remove="Images\UIWidgetFileType.png" />
    <None Remove="Images\Unchecked.png" />
    <None Remove="Images\XMLFile.png" />
    <None Remove="Resources\Meshes\Flag.bin" />
    <None Remove="Resources\Meshes\Sprite.bin" />
    <None Remove="Resources\Meshes\TranslateGizmo.bin" />
    <None Remove="Shaders\GizmoShader.bin" />
    <None Remove="Shaders\GizmoShader.xml" />
    <None Remove="Shaders\LevelShader.bin" />
    <None Remove="Shaders\LevelShader.xml" />
    <None Remove="Shaders\SpriteShader.bin" />
    <None Remove="Shaders\SpriteShader.xml" />
    <None Remove="Shaders\TerrainShader.bin" />
    <None Remove="Shaders\TerrainShader.xml" />
    <None Remove="Resources\Textures\DefaultLayer.dds" />
    <None Remove="Resources\Textures\DefaultLightProbe.dds" />
    <None Remove="Resources\Textures\DefaultSprite.dds" />
    <None Remove="Resources\Textures\Sprites\Conversation.dds" />
    <None Remove="Resources\Textures\Sprites\DirectionalLight.dds" />
    <None Remove="Resources\Textures\Sprites\GameObject.dds" />
    <None Remove="Resources\Textures\Sprites\Location.dds" />
    <None Remove="Resources\Textures\Sprites\PointLight.dds" />
    <None Remove="Resources\Textures\Sprites\RectLight.dds" />
    <None Remove="Resources\Textures\Sprites\SpotLight.dds" />
    <None Remove="Resources\Textures\TranslateGizmo.dds" />
    <None Remove="Resources\Textures\TranslateGizmoSelected.dds" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="xcopy /Y &quot;$(TargetPath)&quot; &quot;$(SolutionDir)bin\Developer\Debug\Plugins\LevelEditorPlugin.dll&quot;" />
  </Target>

  <ItemGroup>
      <Reference Include="EbxClasses" Condition="'$(Configuration)' == 'SWBF2 - Debug' Or '$(Configuration)' == 'SWBF2 - Release'">
        <HintPath>..\..\FrostyEditor\bin\Release\Final\Profiles\StarWarsIISDK.dll</HintPath>
      </Reference>
      <Reference Include="EbxClasses" Condition="'$(Configuration)' == 'MassEffect - Debug' Or '$(Configuration)' == 'MassEffect - Release'">
        <HintPath>..\..\FrostyEditor\bin\Release\Final\Profiles\MassEffectSDK.dll</HintPath>
      </Reference>
      <Reference Include="EbxClasses" Condition="'$(Configuration)' == 'GW2 - Debug' Or '$(Configuration)' == 'GW2 - Release'">
        <HintPath>..\..\FrostyEditor\bin\Release\Final\Profiles\PVZ2SDK.dll</HintPath>
      </Reference>
      <Reference Include="EbxClasses" Condition="'$(Configuration)' == 'GW1 - Debug' Or '$(Configuration)' == 'GW1 - Release'">
          <HintPath>..\..\FrostyEditor\bin\Release\Final\Profiles\PVZ1SDK.dll</HintPath>
      </Reference>
      <Reference Include="EbxClasses">
      </Reference>
      <Reference Include="Microsoft.CSharp" />
      <Reference Include="Newtonsoft.Json">
          <HintPath>..\..\FrostyEditor\bin\Release\Final\Newtonsoft.Json.dll</HintPath>
      </Reference>
      <Reference Include="PresentationCore" />
      <Reference Include="PresentationFramework" />
      <Reference Include="SharpDX">
          <HintPath>..\..\FrostyEditor\bin\Release\Final\ThirdParty\SharpDX.dll</HintPath>
      </Reference>
      <Reference Include="SharpDX.Direct3D11">
          <HintPath>..\..\FrostyEditor\bin\Release\Final\ThirdParty\SharpDX.Direct3D11.dll</HintPath>
      </Reference>
      <Reference Include="SharpDX.DXGI">
          <HintPath>..\..\FrostyEditor\bin\Release\Final\ThirdParty\SharpDX.DXGI.dll</HintPath>
      </Reference>
      <Reference Include="SharpDX.Mathematics">
          <HintPath>..\..\FrostyEditor\bin\Release\Final\ThirdParty\SharpDX.Mathematics.dll</HintPath>
      </Reference>
      <Reference Include="System.Xaml" />
      <Reference Include="WindowsBase" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Add.png" />
    <Resource Include="Images\Bottom.png" />
    <Resource Include="Images\Components.png" />
    <Resource Include="Images\Copy.png" />
    <Resource Include="Images\CurvedWire.png" />
    <Resource Include="Images\GameView.png" />
    <Resource Include="Images\Import.png" />
    <Resource Include="Images\Input.png" />
    <Resource Include="Images\Interface.png" />
    <Resource Include="Images\Timeline.png" />
    <Resource Include="Images\Toolbox.png" />
    <Resource Include="Images\Tracks\AntTrack.png" />
    <Resource Include="Images\Tracks\BoolTrack.png" />
    <Resource Include="Images\Tracks\CameraTrack.png" />
    <Resource Include="Images\Tracks\ColorTrack.png" />
    <Resource Include="Images\Tracks\ConversationTrack.png" />
    <Resource Include="Images\Tracks\DirectorTrack.png" />
    <Resource Include="Images\Tracks\DofTrack.png" />
    <Resource Include="Images\Tracks\EntityTrack.png" />
    <Resource Include="Images\Tracks\EventTrack.png" />
    <Resource Include="Images\Tracks\FaceEmotionTrack.png" />
    <Resource Include="Images\Tracks\FadeTrack.png" />
    <Resource Include="Images\Tracks\FloatTrack.png" />
    <Resource Include="Images\Tracks\LayerTrack.png" />
    <Resource Include="Images\Tracks\LookAtTrack.png" />
    <Resource Include="Images\Tracks\PathTrack.png" />
    <Resource Include="Images\Tracks\TransformTrack.png" />
    <Resource Include="Images\Tracks\Vec2Track.png" />
    <Resource Include="Images\Tracks\Vec3Track.png" />
    <Resource Include="Images\Tracks\Vec4Track.png" />
    <Resource Include="Images\Types\BeamBlueprintFileType.png" />
    <Resource Include="Images\BottomLeft.png" />
    <Resource Include="Images\BottomRight.png" />
    <Resource Include="Images\CaptureThumbnail.png" />
    <Resource Include="Images\ClearLayout.png" />
    <Resource Include="Images\ConnectorOrder.png" />
    <Resource Include="Images\Delay.png" />
    <Resource Include="Images\Float.png" />
    <Resource Include="Images\Types\DetachedSubWorldFileType.png" />
    <Resource Include="Images\Types\EffectBlueprintFileType.png" />
    <Resource Include="Images\Types\GameObjectBlueprintFileType.png" />
    <Resource Include="Images\HoleMask.png" />
    <Resource Include="Images\Instances.png" />
    <Resource Include="Images\Types\LayerDataFileType.png" />
    <Resource Include="Images\Types\LensFlareBlueprintFileType.png" />
    <Resource Include="Images\Types\LevelDataFileType.png" />
    <Resource Include="Images\Types\ObjectBlueprintFileType.png" />
    <Resource Include="Images\Types\PowerBlueprintFileType.png" />
    <Resource Include="Images\Types\ProjectileBlueprintFileType.png" />
    <Resource Include="Images\Schematics.png" />
    <Resource Include="Images\Layers.png" />
    <Resource Include="Images\LevelDataIcon.png" />
    <Resource Include="Images\Properties.png" />
    <Resource Include="Images\Types\SoldierBlueprintFileType.png" />
    <Resource Include="Images\Terrain.png" />
    <Resource Include="Images\ThumbnailSafezone.png" />
    <Resource Include="Images\TopLeft.png" />
    <Resource Include="Images\TopRight.png" />
    <Resource Include="Images\Types\SubWorldFileType.png" />
    <Resource Include="Images\Types\UIWidgetFileType.png" />
    <Resource Include="Images\Types\VehicleBlueprintFileType.png" />
    <Resource Include="Images\Types\VisualEnvironmentFileType.png" />
    <Resource Include="Images\Unchecked.png" />
    <Resource Include="Images\XMLFile.png" />
    <Resource Include="Resources\Meshes\Flag.bin" />
    <Resource Include="Resources\Meshes\Sprite.bin" />
    <Resource Include="Resources\Meshes\TranslateGizmo.bin" />
    <Resource Include="Shaders\GizmoShader.bin" />
    <Resource Include="Shaders\GizmoShader.xml" />
    <Resource Include="Shaders\LevelShader.bin" />
    <Resource Include="Shaders\LevelShader.xml" />
    <Resource Include="Shaders\SpriteShader.bin" />
    <Resource Include="Shaders\SpriteShader.xml" />
    <Resource Include="Shaders\TerrainShader.bin" />
    <Resource Include="Shaders\TerrainShader.xml" />
    <Resource Include="Resources\Textures\DefaultLayer.dds" />
    <Resource Include="Resources\Textures\DefaultLightProbe.dds" />
    <Resource Include="Resources\Textures\DefaultSprite.dds" />
    <Resource Include="Resources\Textures\Sprites\Conversation.dds" />
    <Resource Include="Resources\Textures\Sprites\DirectionalLight.dds" />
    <Resource Include="Resources\Textures\Sprites\GameObject.dds" />
    <Resource Include="Resources\Textures\Sprites\Location.dds" />
    <Resource Include="Resources\Textures\Sprites\PointLight.dds" />
    <Resource Include="Resources\Textures\Sprites\RectLight.dds" />
    <Resource Include="Resources\Textures\Sprites\SpotLight.dds" />
    <Resource Include="Resources\Textures\TranslateGizmo.dds" />
    <Resource Include="Resources\Textures\TranslateGizmoSelected.dds" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    
    <Compile Remove="GameSpecific\starwarsbattlefrontii\**" Condition="'$(Configuration)' != 'SWBF2 - Debug' And '$(Configuration)' != 'SWBF2 - Release'" />
    
    <Compile Remove="GameSpecific\MassEffectAndromeda\**" Condition="'$(Configuration)' != 'MassEffect - Debug' And '$(Configuration)' != 'MassEffect - Release'" />

    <Compile Remove="GameSpecific\GW2.Main_Win64_Retail\**" Condition="'$(Configuration)' != 'GW2 - Debug' And '$(Configuration)' != 'GW2 - Release'" />

    <Compile Remove="GameSpecific\PVZ.Main_Win64_Retail\**" Condition="'$(Configuration)' != 'GW1 - Debug' And '$(Configuration)' != 'GW1 - Release'" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="GameSpecific" />
    <Folder Include="Blender\" />
  </ItemGroup>
  
  <ItemGroup>
    <Page Remove="GameSpecific\starwarsbattlefrontii\**" Condition="'$(Configuration)' != 'SWBF2 - Debug' And '$(Configuration)' != 'SWBF2 - Release'" />
    <Page Remove="GameSpecific\MassEffectAndromeda\**" Condition="'$(Configuration)' != 'MassEffect - Debug' And '$(Configuration)' != 'MassEffect - Release'" />
    <Page Remove="GameSpecific\GW2.Main_Win64_Retail\**" Condition="'$(Configuration)' != 'GW2 - Debug' And '$(Configuration)' != 'GW2 - Release'" />
    <Page Remove="GameSpecific\PVZ.Main_Win64_Retail\**" Condition="'$(Configuration)' != 'GW1 - Debug' And '$(Configuration)' != 'GW1 - Release'" />
  </ItemGroup>

  <ItemGroup>
      <ProjectReference Include="..\..\FrostyControls\FrostyControls.csproj" />
      <ProjectReference Include="..\..\FrostyEditor\FrostyEditor.csproj" />
      <ProjectReference Include="..\..\FrostyHash\FrostyHash.vcxproj" />
      <ProjectReference Include="..\..\FrostyPlugin\FrostyCore.csproj" />
      <ProjectReference Include="..\..\FrostySdk\FrostySdk.csproj" />
      <ProjectReference Include="..\MeshSetPlugin\MeshSetPlugin.csproj" />
      <ProjectReference Include="..\TexturePlugin\TexturePlugin.csproj" />
  </ItemGroup>
  
</Project>